### PR TITLE
add example for eeprom for esp32

### PR DESCRIPTION
**Pull request by Albalate**
Init proyect and use GND to pinout 2 for tare, and GND to 15 to enter 
calibrated mode

### CODE REVIEW

**Comment by RobTillaart** [comment]
This is an EEPROM example like **HX_set_persistent.ino**. 

Primary goal of examples is to explain the library functions and so I am wondering what the difference / added value is of this example.  I saw you extracted the calibrate code in a function.

Did not compare all the details but it looks more like an improvement or an upgrade of the existing example, not necessary a new example. What is the argument to make this an separate example?

**Comment by Albalate** [comment]
the HX_set_persistent.ino does not work with esp32 to read the eeprom.
Today I will do tests with an industrial load cell to see if HX_delta_scale.ino does it correctly, I think it does not work.
eeprom for esp32 need to initialize the eeprom in setup.

**Comment by Albalate** [comment]
tests performed:
utilcell 30 KG load cell (https://www.utilcell.es/load-cell/300-model-load-cell/)
hx711
esp32
result: +-150 units(gr))
#####################################
utilcell 30 KG load cell (https://www.utilcell.es/load-cell/300-model-load-cell/)
hx711
arduino UNO R3
result: +-3  units(gr))
soft:
//
//    FILE: HX_kitchen_scale.ino
//  AUTHOR: Rob Tillaart
// PURPOSE: HX711 demo
//     URL: https://github.com/RobTillaart/HX711

**Comment by RobTillaart** [comment]
I see difference  3gr and 150 gr.

What voltage is applied to load cell? is it the same in both cases?

**Comment by Albalate** [comment]
voltage to hx711 is 5v in both cases (supply is stabilized with 2 output filters)
more than a difference, I would say that it is a random measure in esp32

**Comment by RobTillaart** [comment]
Strange as the HX711 does the AD conversion and the  communication to the processor is binary.
Do you have a logic analyzer to capture the bits?

**Comment by Albalate** [comment]
I have the oscilloscope broken, it is due to the speed of the processor, with the library of "https://github.com/bogde/HX711" I get the same result in both hardware. +-4 gr whit scale off 30000gr
When I have a while I'll help you find the error

**Comment by RobTillaart** [comment]
Mmm, difference between Bogdes lib and mine is using long versus float for the math. 
As the UNO with my lib gives the same results as Bogdes lib (within noise limits) the math is OK.

Can you print the raw values that are read from the HX711 by means of shiftin.

**Comment by RobTillaart** [comment]
30.000 grams loadcell. 
~4gr is an accuracy of ~1 in 10.000 (quite good)
What says the datasheet? Do you have a link?

**Comment by Albalate** [comment]
in esp32 not work only work in arduino UNO
When I finish the current work, I help you find the mistake, I understand that it may be mine

**Comment by RobTillaart** [comment]
> When I finish the current work, I help you find the mistake, I understand that it may be mine

Any progress made?

**Comment by RobTillaart** [comment]
Any progress made?
If not I better close this Pull Request

**Pull request closed without merging**
